Repository bcgov/CONN-CCBC-portal, pull requests merged in 2022-07, with the labels that each got.

#259 fix: form text formatting
  .github/actions/app/action.yaml
  .github/actions/dev-env-setup/action.yml
  app/formSchema/pages/benefits.ts
  app/formSchema/pages/budgetDetails.ts
  app/formSchema/pages/declarations.ts
  app/formSchema/pages/declarationsSign.ts
  app/formSchema/pages/existingNetworkCoverage.ts
  app/formSchema/pages/mapping.ts
  app/formSchema/pages/organizationProfile.ts
  app/formSchema/pages/projectPlan.ts
  app/formSchema/uiSchema.ts
  db/deploy/functions/session.sql
  db/revert/create_roles.sql
  db/test/tables/table_applications_test.sql
  db/test/tables/table_connect_session_test.sql
  docs/Definition_of_ Ready.md
  docs/Team_Agreements.md
  helm/app/.helmignore
Labels: Task

#227 GraphQL Schema Sync Guardrails
  .github/actions/dev-env-setup/action.yml
  .github/actions/local-app-run/action.yaml
  .github/workflows/publish_deploy_image.yaml
  .github/workflows/tests.yaml
  Makefile
  app/schema/schema.graphql
Labels: Task, inSprint

#340 chore: fix relay ssr setup
  app/.babelrc
  app/__generated__/PageQuery.graphql.ts
  app/__generated__/createAttachmentMutation.graphql.ts
  app/__generated__/dashboardQuery.graphql.ts
  app/__generated__/deleteAttachmentMutation.graphql.ts
  app/__generated__/getApplicationByIdQuery.graphql.ts
  app/__generated__/pagesQuery.graphql.ts
  app/__generated__/successQuery.graphql.ts
  app/components/Dashboard/Table.tsx
  app/lib/relay/withRelayOptions.tsx
  app/next.config.js
  app/pages/_app.tsx
  app/pages/_document.tsx
  app/pages/dashboard.tsx
  app/pages/form/[id]/[page].tsx
  app/pages/form/[id]/success.tsx
  app/pages/index.tsx
  app/schema/queries/getAllApplicationsByOwnerQuery.ts
  app/schema/queries/getApplicationById.ts
  app/schema/queries/getSessionQuery.ts
  app/schema/queries/index.ts
Labels: tech debt, inSprint
